use std::time::Instant;

#[derive(Debug)]
pub struct CloneReport {
    pub compression_backend: &'static str,
    pub ref_count: usize,
    pub pack_bytes: u64,
    pub total_ms: u128,
    pub clone_wall_ms: u128,
    pub clone_unreported_ms: u128,
    pub discovery_ms: u128,
    pub fetch_ms: u128,
    pub fetch_request_ms: u128,
    pub fetch_first_byte_ms: u128,
    pub fetch_sideband_read_ms: u128,
    pub fetch_pack_write_ms: u128,
    pub fetch_pack_flush_ms: u128,
    pub fetch_checksum_ms: u128,
    pub fetch_frame_send_wait_ms: Option<u128>,
    pub pack_receive_bytes_per_sec: u64,
    pub ingest_ms: u128,
    pub pack_scan_ms: u128,
    pub pack_resolve_ms: u128,
    pub pack_idx_write_ms: u128,
    pub pack_object_state_ms: u128,
    pub pack_object_count: usize,
    pub pack_base_object_count: usize,
    pub pack_delta_count: usize,
    pub pack_offset_delta_count: usize,
    pub pack_ref_delta_count: usize,
    pub pack_declared_inflated_bytes: u64,
    pub streaming_pack_scan: bool,
    pub checkout_ms: u128,
    pub checkout_manifest_ms: u128,
    pub checkout_dir_create_ms: u128,
    pub checkout_file_materialize_ms: u128,
    pub checkout_index_write_ms: u128,
    pub checkout_file_count: usize,
    pub checkout_dir_count: usize,
    pub checkout_blob_bytes: u64,
    pub retained_object_count: usize,
    pub retained_object_bytes: usize,
    pub spilled_object_count: usize,
    pub spilled_object_bytes: usize,
    pub checkout_needed_blob_count: usize,
    pub checkout_ready_blob_count: usize,
    pub checkout_ready_blob_bytes: usize,
    pub checkout_spilled_blob_count: usize,
    pub checkout_spilled_blob_bytes: usize,
    pub checkout_missing_blob_count: usize,
    pub reconstructed_object_count: usize,
    pub pipeline_enabled: bool,
    pub pipeline_frame_count: Option<usize>,
    pub pipeline_checkout_wait_ms: Option<u128>,
    pub pipeline_checkout_wait_count: Option<usize>,
    pub pipeline_checkout_wait_max_ms: Option<u128>,
    pub pipeline_peak_pending_delta_count: Option<usize>,
    pub pipeline_resolver_wall_ms: Option<u128>,
    pub pipeline_resolver_wait_for_frame_ms: Option<u128>,
    pub pipeline_queue_peak_depth: Option<usize>,
    pub pipeline_arena_spill_bytes: Option<u64>,
    pub finalize_ms: u128,
    pub target_size_scan_ms: u128,
    pub target_bytes: u64,
    pub rss_bytes: Option<u64>,
}

pub fn measure_ms<T>(operation: impl FnOnce() -> T) -> (T, u128) {
    let start = Instant::now();
    let result = operation();
    (result, start.elapsed().as_millis())
}
